version: "3"
services:
  app_react:
    build: ./linkr/linkr-front
    container_name: linkr_react
    volumes:
      - build_react:/var/www/html
    depends_on:
      - linkr_server

  linkrDB:
    image: postgres:13
    container_name: linkrDB
    env_file:  
      - .env
    ports:
      - 2345:${POSTGRES_PORT}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  
  linkr_server: 
    build: ./linkr/linkr-back
    container_name: linkr_server
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - ${POSTGRES_IMAGE_DB_DOCKER}
    volumes: 
    - ./linker/linkr_server:/usr/src
    - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://${POSTGRES_IMAGE_DB_DOCKER}:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    
  nginx:
    build: ./linkr/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  postgres:
  build_react:
